CREATE SEQUENCE TEST_SEQ NOCACHE;

CREATE TABLE TEST_T (
	id	NUMBER	PRIMARY KEY,
	name VARCHAR2(256)	NOT NULL,
	age NUMBER	NOT NULL
);

INSERT INTO TEST_T VALUES(TEST_SEQ.NEXTVAL, '홍길동', 32);
INSERT INTO TEST_T VALUES(TEST_SEQ.NEXTVAL, '김철수', 28);
INSERT INTO TEST_T VALUES(TEST_SEQ.NEXTVAL, '박연우', 35);